version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pr_reviewer_app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_WRITE_TIMEOUT: ${SERVER_WRITE_TIMEOUT}
      SERVER_READ_TIMEOUT: ${SERVER_READ_TIMEOUT}
      SERVER_IDLE_TIMEOUT: ${SERVER_IDLE_TIMEOUT}
      MIGRATIONS_PATH: ${MIGRATIONS_PATH}
    ports:
      - "8080:${SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - reviewer-network
    command: sh -c "./migrate && ./main"

  db:
    image: postgres:15-alpine
    container_name: pr_reviewer_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - reviewer-network

networks:
  reviewer-network:
    driver: bridge

volumes:
  postgres_data: